name: Deploy Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          sudo apt-get install elfutils -y
          sudo apt install rpm
          npm install -g node-gyp
          npm install
          rm -rf node_modules/sharp
          SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc --build-from-source sharp
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run publish-linux-app

  macos:
    runs-on: macos-latest-large
    env:
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      TEAMID: ${{ secrets.TEAMID }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROVISION_PROFILE: ${{ secrets.PROVISION_PROFILE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          rm -rf node_modules/sharp
          echo -n "$PROVISION_PROFILE" | base64 --decode > embedded.provisionprofile
          npm install --platform=darwin --arch=x64 sharp
          npm rebuild --platform=darwin --arch=arm64 sharp
          npm run publish-mac-universal-app

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run publish-win-app
